
const items = [
    {
        id: '001',
        image: 'https://www.bhphotovideo.com/images/images1000x1000/nikon_1527_df_dslr_camera_with_1013094.jpg',
        company: 'Nikon',
        item_name: 'Nikon COOLPIX A300 Point & Shoot Camera 20.1 MP',
        original_price: 1045,
        current_price: 606,
        discount: 42,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.5,
            count: 1400,
        },
    },
    {
        id: '002',
        image: 'https://tse4.explicit.bing.net/th?id=OIP.SdhF4RXDxV3ChR_A31c3UgHaJS&pid=Api&P=0&h=180',
        company: 'Blue Heaven ',
        item_name: 'Blue Heaven Festive Fair Tone Make Up Kit - Vanilla (10Pcs)',
        original_price: 2599,
        current_price: 1507,
        discount: 42,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.3,
            count: 24,
        },
    },
    {
        id: '003',
        image: 'https://tse4.mm.bing.net/th?id=OIP.UkE7GWWIrPlZkwEUPBKepwHaE8&pid=Api&P=0&h=180',
        company: 'HERO',
        item_name: 'Calcuttacycleco Hero Cycles For Mens And Boys 27.5 T Mountain/Hardtail Cycle',
        original_price: 15999,
        current_price: 9495,
        discount: 39,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.1,
            count: 249,
        },
    },
    {
        id: '004',
        image: 'http://ksassets.timeincuk.net/wp/uploads/sites/54/2016/12/macbook-pro-13-2022-1.jpg',
        company: 'apple',
        item_name: 'macbook m1',
        original_price: 99999,
        current_price: 89999,
        discount: 0,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 5.0,
            count: 10,
        },
    },
    {
        id: '005',
        image: 'https://tse1.mm.bing.net/th?id=OIP.sVEzl8eqi5u4jO5m2Z8QcQHaG7&pid=Api&P=0&h=180',
        company: 'Roadster',
        item_name: 'Pure Cotton T-shirt',
        original_price: 1399,
        current_price: 489,
        discount: 65,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.2,
            count: 3500,
        },
    },
    {
        id: '006',
        image: 'https://www.bhphotovideo.com/images/images2500x2500/apple_mj2x2ll_a_watch_sport_smartwatch_38mm_1187194.jpg',
        company: 'watch',
        item_name: 'Men ReactX watch',
        original_price: 14995,
        current_price: 14995,
        discount: 0,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 0.0,
            count: 0,
        },
    },
    {
        id: '007',
        image: 'https://cdn00.nnnow.com/web-images/preview/styles/WFWZ3XXUA8P/1561109645638/1.jpg',
        company: 'The Indian Garage Co',
        item_name: 'Men Slim Fit Regular Shorts',
        original_price: 1599,
        current_price: 639,
        discount: 60,
        rating: {
            stars: 4.2,
            count: 388,
        },
    },
    {
        id: '008',
        image: 'https://www.luluhypermarket.com/medias/834111-01.jpg-1200Wx1200H?context=bWFzdGVyfGltYWdlc3w0NDg0MTJ8aW1hZ2UvanBlZ3xpbWFnZXMvaGVlL2g3MC85MTE4MDI0OTU3OTgyLmpwZ3wwNmZiMjNlYmE5ODM1Yjk0N2UxYzg0NGU3MWQ4MGFkOTJhY2RjODFiYTY4OGM3N2NkMjMwMmY4Yjg1MmE5NTMx',
        company: 'Nivea',
        item_name: 'Men Fresh Deodrant 150ml',
        original_price: 285,
        current_price: 142,
        discount: 50,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.2,
            count: 5200,
        },
    }
];
